CXX := g++-12
CXXFLAGS := -O3 -std=c++20 -static-libstdc++
LDFLAGS := -lbenchmark -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_highgui -lcrypto -lssl
INCLUDES := -Iinclude -I/usr/local/include/opencv4 -I/usr/local/include/llfio -I/usr/local/include/openssl
SRC := $(shell find src -name '*.cpp') bench.cpp
OBJS := $(SRC:.cpp=.o)
DEPS := $(OBJS:.o=.d)
EXECUTABLE := VWTChunkloadingTestingAndBenching

all: $(EXECUTABLE)

VWT: $(OBJS)
	$(CXX) $(OBJS)  -o run.out $(LDFLAGS)

-include $(DEPS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -MMD -c $< -o $@

clean:
	rm -f $(OBJS) $(EXECUTABLE) $(DEPS)

.PHONY: all clean
