#ifndef VWTCHUNKLOADINGTESTINGANDBENCHING_MODEL_CHUNKCOORDINATE_H
#define VWTCHUNKLOADINGTESTINGANDBENCHING_MODEL_CHUNKCOORDINATE_H

#include <cstdint>
#include "position.h"

using ChunkCoordinate = Position3d;

#endif //VWTCHUNKLOADINGTESTINGANDBENCHING_MODEL_CHUNKCOORDINATE_H
