#ifndef VWTCHUNKLOADINGTESTINGANDBENCHING_MODEL_MASK_H
#define VWTCHUNKLOADINGTESTINGANDBENCHING_MODEL_MASK_H

#include <vector>

struct Mask
{
	uint64_t width, height;

	std::vector<bool> data;
};

#endif //VWTCHUNKLOADINGTESTINGANDBENCHING_MODEL_MASK_H
