#ifndef VWTCHUNKLOADINGTESTINGANDBENCHING_MODEL_TIFFILE_H
#define VWTCHUNKLOADINGTESTINGANDBENCHING_MODEL_TIFFILE_H

struct TifFile
{
	uint64_t width, height;

	std::vector<uint16_t> data;
};

#endif //VWTCHUNKLOADINGTESTINGANDBENCHING_MODEL_TIFFILE_H
